### ISSUE TITLE
Why not objects?

### ISSUE THREAD

**Issue by Chuckame** [nfrawley93/dart_geohash#7]
Hey,

Thanks for your work.

Is there any reason of using list with 2 items (lon & lat) instead of an object with specific fields ? If not, I can make a PR if you want !

**Comment by nfrawley93** [comment]
Honestly it was because I spun this off as its only thing while I was working on a different project. At some point I felt it was complete enough to publish. I didn't spend all that much time trying to make as good as it deserves!
I know you posted this a while ago but feel free to make a PR if you want. I'd be happy to take a look. This is mostly at a place were it will likely just be fixed for dart support unless I feel the need to rewrite it

**Comment by ethicnology** [comment]
I would support named parameters for latitude and longitude since it could create confusion regarding the order or the given params
